{
 "title": "Dragonfly-Scheduler",
 "description": "Grafana dashboard for dragonfly scheduler.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_scheduler_version{}) by (git_version, git_commit)",
     "legendFormat": "{{git_version}}-{{git_commit}}"
    }
   ]
  },
  {
   "title": "Concurrent Scheduling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(dragonfly_scheduler_concurrent_schedule_total{}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "GRPC QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_service=\"scheduler.Scheduler\"}[$interval]))"
    }
   ]
  },
  {
   "title": "GRPC request code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service=\"scheduler.Scheduler\",grpc_type=\"unary\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_method}}/{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Announce Peer QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_announce_peer_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "Announce Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_announce_peer_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Announce Peer Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_announce_peer_failure_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stat Peer QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_stat_peer_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "Stat Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_stat_peer_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stat Peer Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_stat_peer_failure_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leave Peer QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_leave_peer_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "Leave Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_leave_peer_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leave Peer Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_leave_peer_failure_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stat Task QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_stat_task_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "Stat Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_stat_task_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stat Task Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_stat_task_failure_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Announce Host QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_announce_host_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "Announce Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_announce_host_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Announce Host Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_announce_host_failure_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leave Host QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_leave_host_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "Leave Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_leave_host_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leave Host Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_leave_host_failure_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{container=\"scheduler\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"scheduler\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "{{instance}}-resident"
    },
    {
     "expr": "process_virtual_memory_bytes{container=\"scheduler\"}",
     "legendFormat": "{{instance}}-virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{container=\"scheduler\"}",
     "legendFormat": "{{instance}}-bytes_allocated"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{container=\"scheduler\"}",
     "legendFormat": "{{instance}}-stack_inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"scheduler\"}",
     "legendFormat": "{{instance}}-heap_inuse"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{container=\"scheduler\"}[30s])",
     "legendFormat": "{{instance}}-alloc_rate"
    }
   ]
  }
 ]
}