{
 "title": "Dragonfly-Manager",
 "description": "Grafana dashboard for dragonfly manager.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dragonfly_manager_version{}) by (git_version, git_commit)",
     "legendFormat": "{{git_version}}-{{git_commit}}"
    }
   ]
  },
  {
   "title": "GRPC QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_service=\"manager.Manager\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Search Scheduler Cluster QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_search_scheduler_cluster_total{}[$interval]))"
    }
   ]
  },
  { "title": "GRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GRPC request code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_service=\"manager.Manager\",grpc_type=\"unary\"}[$interval])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_method}}/{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Search Scheduler Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_search_scheduler_cluster_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Search Scheduler Cluster Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_scheduler_exchange_peer_failure_total{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "REST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "REST request code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_requests_total{url!=\"/healthy/\"}[$interval])) by (code, method, url)",
     "legendFormat": "{{method}}-{{url}}-{{code}}"
    }
   ]
  },
  {
   "title": "REST QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dragonfly_manager_requests_total{}[$interval]))"
    }
   ]
  },
  {
   "title": "REST Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(dragonfly_manager_request_duration_seconds_sum{}[$interval]) * 1000 * 1000 / increase(dragonfly_manager_request_duration_seconds_count{}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{container=\"manager\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"manager\"}",
     "legendFormat": "{{instance}}-{{quantile}}"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "{{instance}}-resident"
    },
    {
     "expr": "process_virtual_memory_bytes{component=\"manager\"}",
     "legendFormat": "{{instance}}-virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{container=\"scheduler\"}",
     "legendFormat": "{{instance}}-bytes_allocated"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{container=\"manager\"}",
     "legendFormat": "{{instance}}-stack_inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"manager\"}",
     "legendFormat": "{{instance}}-heap_inuse"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{container=\"manager\"}[30s])",
     "legendFormat": "{{instance}}-alloc_rate"
    }
   ]
  }
 ]
}